### ISSUE TITLE
Connection details get ignored

### ISSUE THREAD

**Issue by TetPX** [Stuyk/simplymongo#1]
It attempts to connect to a constant url always and if a username and password are provided it tried to use a config variable that doesn't exist:

https://github.com/Stuyk/simplymongo/blob/740323733cd847c46b43e7c759d07a3a9ff61680/index.js#L52-L59

**Comment by Stuyk** [comment]
Pending Review for https://github.com/Stuyk/simplymongo/commit/0d3b899703d7a84228cbd668a39ced7424a6fbbb
